name: easy_http_request
version: 0.0.1
description: A new Flutter package project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies: 
  dio: 4.0.0
  dio_http_formatter: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  faker: 2.0.0
  lint: 1.5.3
  flutter_test: 
    sdk: flutter

flutter: null
