name: with_get_it_dependency_injection
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_it: 7.2.0
  easy_http_request: 
    path: ../../
  flutter: 
    sdk: flutter

dev_dependencies: 
  faker: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true