include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: 
    - build/**, 
    - example/**
    
linter:
  rules:
    lines_longer_than_80_chars: false
    comment_references: false
    sort_pub_dependencies: false
    # I decided to add this, although I use cascading invocation, 
    # but in the code of adding headers if I use it it gives me an immutability error
    cascade_invocations: false 