include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [build/**, test/**, example/**]

linter:
  rules:
    lines_longer_than_80_chars: false
    comment_references: false
    sort_pub_dependencies: false
    