name: easy_http_request
description: A package that simplifies the queries to the apis or web services, you focus on creating the model, this package takes care of the rest.
version: 1.0.3

repository: https://github.com/ocb-dev-04/easy_http_request

environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  dio: ^4.0.0
  dio_http_formatter: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  faker: 2.0.0
  very_good_analysis: 2.2.0
  flutter_test: 
    sdk: flutter
